Repository unibas-tilics/tilics, pull requests merged in 2019-08, with the labels that each got.

#1 Article 013: Exclusive OR
  articles/article-013-exclusive-or.md
  images/image-013-exclusive-or.svg
Labels: Done, Website, final16, final32

#4 Article 063: Reverse Engineering
  articles/article-063-reverse-engineering.md
  images/image-063-reverse-engineering.svg
Labels: Done, Website, final16, final32

#6 Article 083: Being lazy is a good thing
  articles/article-083-being-lazy-is-a-good-thing.md
  images/image-083-being-lazy-is-a-good-thing.svg
Labels: Done, Website, final16, final32

#10 Article 032: Deadlock
  articles/article-032-deadlock.md
  images/image-032-deadlock.svg
Labels: Done, Website, final16, final32

#11 Article 109: world of triangles
  articles/article-109-world-of-triangles.md
  images/image-109-world-of-triangles.svg
Labels: Done, Website, final16, final32

#15 Article 007: null
  articles/article-007-null.md
  images/image-007-null.svg
Labels: Done, Website, final16, final32

#20 Article 086: year 2038 problem
  articles/article-086-year-2038-problem.md
  images/image-086-year-2038-problem.svg
Labels: Done, Website, final16, final32

#24 Article 039: computer scientists confuse halloween
  articles/article-039-computer-scientist-confuse-halloween.md
  images/image-039-computer-scientist-confuse-halloween.svg
Labels: Done, Website, final32

#30 Article 019: The Turing Machine
  articles/article-019-the-turing-machine.md
  images/image-019-the-turing-machine.svg
Labels: Done, Website, final16, final32

#31 Article 118: State Machines
  articles/article-118-state-machines.md
  images/image-118-state-machines.svg
Labels: Done, Website, final16, final32

#36 Article 079: Why do programmers need forks?
  articles/article-079-fork.md
  images/image-079-fork.svg
Labels: Done, Website, final32

#38 Article 058: Mutex
  articles/article-058-mutex.md
  images/image-058-mutex.svg
Labels: Done, Website, final32

#43 Article 122: ASCII
  articles/article-122-ascii.md
  images/image-122-ascii.svg
Labels: Done, Website, final32

#45 Article 046: Overflow
  articles/article-046-overflow.md
  images/image-046-overflow.svg
Labels: Done, Website, final32

#46 Article 031: Greedy algorithm
  articles/article-031-greedy-algorithm.md
  images/image-031-greedy-algorithm.svg
Labels: Done, Website, final32

#52 Article 038: Turing Test
  articles/article-038-turing-test.md
  images/image-038-turing-test.svg
Labels: Done, Website, final32

#53 Article 055: Turing Completeness
  articles/article-055-turing-completeness.md
  images/image-055-turing-completeness.svg
Labels: Done, Website

#55 Article 124: Counting systems
  articles/article-124-counting-systems.md
  images/image-124-counting-systems.svg
Labels: Done, Website, final32

#56 Article 050: Hello World
  articles/article-050-hello-world.md
  images/image-050-hello-world.svg
Labels: Done, Website, final16, final32

#48 Article 047: Game of Life
  articles/article-047-game-of-life.md
  images/image-047-game-of-life.svg
Labels: Done, Website

#42 Article 116: Esoteric Programming Languages
  articles/article-116-esoteric-programming-languages.md
  images/image-116-esoteric-programming-languages.svg
Labels: Done, Website

#39 Article 104: Monte Carlo Methods
  articles/article-104-monte-carlo-methods.md
  images/image-104-monte-carlo-methods.svg
Labels: Done, Website, final16, final32

#35 Article 117: Why Stick to one Example
  articles/article-117-Why-stick-to-one-example.md
  images/image-117-why-stick-to-one-example.svg
Labels: Done, Website

#8 Article 088: No Free Lunch
  articles/article-088-no-free-lunch.md
  images/image-088-no-free-lunch.svg
Labels: Done, Website

#12 Article 111: Counting to more than ten with two hands
  articles/article-111-counting-to-more-than-ten-with-two-hands.md
  images/image-111-counting-to-more-than-ten-with-two-hands.svg
Labels: Done, Website, final16, final32

#57 Article 125: Euler Path
  articles/article-125-euler-path.md
  images/image-125-euler-path.svg
Labels: Done, Website

#27 Article 076: Always use a VCS
  articles/article-076-VCS.md
  images/image-076-VCS.svg
Labels: Done, Website, final16, final32

#34 Article 030: Big O Notation
  articles/article-030-big-o-notation.md
  images/image-030-big-o-notation.svg
Labels: Done, Website, final32

#22 Article 110: Guess Fast or Wait
  articles/article-110-guess-fast-or-wait.md
  images/image-110-guess-fast-or-wait.svg
Labels: Done, Website, final32

#40 Article 100: Errors propagate!
  articles/article-100-errors-propagate.md
  images/image-100-errors-propagate.svg
Labels: Done, Website, final32
