Repository unibas-tilics/tilics, pull requests merged in 2019-09, with the labels that each got.

#49 Article 060: Handshake
  articles/article-060-handshake.md
  images/image-060-handshake.svg
Labels: Done, Website, final32

#47 Article 065: Information hiding
  articles/article-065-information-hiding.md
  images/image-065-information-hiding.svg
Labels: Done, Website, final32

#41 Article 121: Quine
  articles/article-121-quine.md
  images/image-121-quine.svg
Labels: Done, Website, final32

#37 Article 002: Camel Case
  articles/article-002-camel-case.md
  images/image-002-camel-case.svg
Labels: Done, Website, final16, final32

#25 Article 114: Why Uptime Matters
  articles/article-114-why-uptime-matters.md
  images/image-114-why-uptime-matters.svg
Labels: Done, Website, final16, final32

#17 Article 052: Patch
  articles/article-052-patch.md
  images/image-052-patch.svg
Labels: Done, Website, final32

#16 Article 033: Brute force
  articles/article-033-brute-force.md
  images/image-033-brute-force.svg
Labels: Done, Website, final32

#14 Article 093: Rice's Theorem
  articles/article-093-rices-theorem.md
  images/image-093-rices-theorem.svg
Labels: Done, Website

#3 Article 025: We all hate Bugs
  articles/article-025-we-all-hate-bugs.md
  images/image-025-we-all-hate-bugs.svg
Labels: Done, Website, final16, final32
